"""Add photo fields to secret_messages

Revision ID: 5628210295ef
Revises: 
Create Date: 2026-04-25 09:46:57.597952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5628210295ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secret_messages', sa.Column('photo_file_id', sa.String(), nullable=True))
    op.add_column('secret_messages', sa.Column('photo_caption', sa.String(), nullable=True))
    op.alter_column('secret_messages', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('secret_messages', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('secret_messages', 'photo_caption')
    op.drop_column('secret_messages', 'photo_file_id')
    # ### end Alembic commands ###
